# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    article_directory: '%kernel.project_dir%/var/uploads/articles'
    magazine_directory: '%kernel.project_dir%/var/uploads/magazines'

services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    EditorialBundle\:
        resource: '../../src/EditorialBundle/*'
        exclude: '../../src/EditorialBundle/{Entity,Repository,Tests}'

    EditorialBundle\Controller\:
        resource: '../../src/EditorialBundle/Controller'
        public: true
        tags: ['controller.service_arguments']

    EditorialBundle\Factory\ResponseFactory:
        arguments:
            $articleDirectory: '%article_directory%'
            $magazineDirectory: '%magazine_directory%'
