<?php

namespace EditorialBundle\Repository;

/**
 * ArticleVersionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleVersionRepository extends \Doctrine\ORM\EntityRepository
{
}
