<?php

namespace EditorialBundle\Repository;

/**
 * ArticleAuthorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleAuthorRepository extends \Doctrine\ORM\EntityRepository
{
}
