<?php

namespace EditorialBundle\Repository;

/**
 * MagazineTopicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MagazineTopicRepository extends \Doctrine\ORM\EntityRepository
{
}
